---
resource_types:
  - name: custom-docker-image-resource
    type: docker-image
    privileged: true
    source:
      repository: jaedle/custom-docker-image-resource
      tag: latest

resources:
  - name: source-code
    type: git
    source:
      uri: git@github.com:jaedle/docker-image-resource.git
      private_key: ((ci-key))

  - name: custom-docker-image-resource
    type: docker-image
    source:
      repository: jaedle/custom-docker-image-resource
      username: ((docker-username))
      password: ((docker-password))

  - name: smoke-test-image
    type: custom-docker-image-resource
    source:
      repository: jaedle/smoke-test-image
      username: ((docker-username))
      password: ((docker-password))
      remote_docker:
        host: ((remote-docker-host))
        ssh_key: ((remote-docker-ssh-key))



jobs:
  - name: build
    plan:
      - get: source-code
        trigger: true
      - put: custom-docker-image-resource
        params:
          build: source-code/
          dockerfile: source-code/dockerfiles/alpine/Dockerfile

  - name: smoke-test
    plan:
      - get: source-code
      - put: smoke-test-image
        params:
          build: source-code/dockerfiles/smoke-test-image
